### ISSUE TITLE
Capture_Images_Script.py stuck in loop

### ISSUE THREAD

**Issue by tremmert81** [Seeed-Studio/Seeed_Arduino_GroveAI#1]
Hello,
I am currently running Python 3.7.3 under Windows 10.  When I run the script, it seems to get stuck in a loop:

`**************************************************
looking for device!
ID 1bcf:28ae Bus 002->1->6 Device 4
ID 8086:9ca6 Bus 002 Device 0
ID 8087:8001 Bus 002->1 Device 2
ID 8087:0a2a Bus 002->1->3 Device 3
ID 8086:9cb1 Bus 001 Device 0
←[4;31mID 2886:8061 Bus 001->2 Device 15 ←[0mdevice is connected
Resetting device...
Device has been reset!
**************************************************
looking for device!
ID 1bcf:28ae Bus 002->1->6 Device 4
ID 8086:9ca6 Bus 002 Device 0
ID 8087:8001 Bus 002->1 Device 2
ID 8087:0a2a Bus 002->1->3 Device 3
ID 8086:9cb1 Bus 001 Device 0
←[4;31mID 2886:8061 Bus 001->2 Device 15 ←[0mdevice is connected
Resetting device...
**************************************************`

The script did create a directory called save_img, but it remains empty.

**Comment by taunoe** [comment]
Does it have the correct firmware?
Or is it connected to the website? Close it.

When I run the firmware and python script it works on Windows.
**************************************************
looking for device!
ID 2886:8060 Bus 001->3->3 Device 9 CLOSED
ID 8086:a3af Bus 001 Device 0
ID 0403:6014 Bus 001->5->2 Device 6
ID 10de:1ada Bus 002 Device 0
ID 056a:0390 Bus 001->5->1 Device 5
ID 0424:2514 Bus 001->3 Device 1
ID 046d:c092 Bus 001->6 Device 4
ID 056a:0395 Bus 001->5 Device 2
ID 04d9:0296 Bus 001->4 Device 3
Resetting device...
Device has been reset!
**************************************************
looking for device!
ID 2886:8060 Bus 001->3->3 Device 9 device is connected
Resetting device...
**************************************************
looking for device!
ID 2886:8060 Bus 001->3->3 Device 9 device is connected
Number of saved pictures on device 0：21

**Comment by mjq2020** [comment]
> 



> Hello, I am currently running Python 3.7.3 under Windows 10. When I run the script, it seems to get stuck in a loop:
> 
> `************************************************** looking for device! ID 1bcf:28ae Bus 002->1->6 Device 4 ID 8086:9ca6 Bus 002 Device 0 ID 8087:8001 Bus 002->1 Device 2 ID 8087:0a2a Bus 002->1->3 Device 3 ID 8086:9cb1 Bus 001 Device 0 ←[4;31mID 2886:8061 Bus 001->2 Device 15 ←[0mdevice is connected Resetting device... Device has been reset!
> 
> looking for device! ID 1bcf:28ae Bus 002->1->6 Device 4 ID 8086:9ca6 Bus 002 Device 0 ID 8087:8001 Bus 002->1 Device 2 ID 8087:0a2a Bus 002->1->3 Device 3 ID 8086:9cb1 Bus 001 Device 0 ←[4;31mID 2886:8061 Bus 001->2 Device 15 ←[0mdevice is connected Resetting device... **************************************************`
> 
> The script did create a directory called save_img, but it remains empty.

The firmware you burned should be wrong, please follow the instructions below to burn the correct firmware.
  1)  If your device is sensecap, please burn this [sensecap_ai_capture_firmware_v01-00.uf2](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/download/v1.0.0/sensecap_ai_capture_firmware_v01-00.uf2) firmware.
  2)  If your device is grove, please burn this [grove_ai_capture_firmware_v01-00.uf2](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/download/v1.0.0/grove_ai_capture_firmware_v01-00.uf2) firmware 
  3) Just run it again.

Other firmware can be found [https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/tag/v1.0.0](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/tag/v1.0.0)

**Comment by mjq2020** [comment]
Hello, if there are no other questions, we will close this issue. If you have any questions, please feel free to ask.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
