### ISSUE TITLE
Support for raspberry pi camera module V3

### ISSUE THREAD

**Issue by hatrinh-sj** [Seeed-Studio/Seeed_Arduino_GroveAI#10]
Hi @LynnL4,

Raspberry Pi camera module V3 has a nice auto-focus feature. It's based on sensor IM708. I see https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2 supported it already. Please add support IM708 for Grove Vision AI module V2 in its default firmware.

**Comment by Pillar1989** [comment]
@hatrinh-sj https://github.com/Seeed-Studio/SSCMA-Micro/blob/dev/porting/himax/we2/drivers/IMX708_mipi_2lane_2304x1296.i IM708 actually we have support on v2, but because the himax chip does not have ISP function, so even if the hardware has this property, it can not support the autofocus function.

**Comment by Pillar1989** [comment]
@hatrinh-sj  If there are more questions, I suggest that it is better to discuss under the corresponding software repo.

**Comment by hatrinh-sj** [comment]
I apologize for posting it here. I didn't know the correct repo to post. I will re-post in the repo you mentioned.
