### ISSUE TITLE
Creating a Custom Model is Broken

### ISSUE THREAD

**Issue by CharlesMod** [Seeed-Studio/Seeed_Arduino_GroveAI#2]
**Describe the bug**
Currently attempting to follow [the example google collab document](https://colab.research.google.com/gist/lakshanthad/b47a1d1a9b4fac43449948524de7d374/yolov5-training-for-sensecap-a1101.ipynb) results in an error at step 7, this is due to changes in FlatBuffers that is resulting in a critical error: 
`
“TensorFlow Lite: export failure: EndVector() missing 1 required positional argument: ‘vectorNumElems’”`

Since step 7 does not complete successfully, all subsequent steps fail. 

**To Reproduce**
1. Go to the example doc above
2. Click on fill in the information for the custom training set from robotflow
3. Run All

**Expected behavior**
Run all should run the whole document through, and result in a usable model file, however the execution stops at step 7. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11051814/218876721-1eb086cf-7615-4516-bd34-f7dafb098f91.png)
![image](https://user-images.githubusercontent.com/11051814/218876807-07d1fad5-7d26-413c-bddd-20b769b04210.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox, Chrome
 - Version 109.0.1

**Comment by CharlesMod** [comment]
turned out to be an issue of flatbuffers v1.12 being forced in export.py of the transfer

**Comment by CharlesMod** [comment]
Sorry, didn't mean to close this

**Comment by LynnL4** [comment]
Hi, It is recommended to use the latest mod assistant for training
https://github.com/Seeed-Studio/ModelAssistant
https://github.com/Seeed-Studio/sscma-model-zoo

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
