### ISSUE TITLE
Unable to flash edge impulse firmware

### ISSUE THREAD

**Issue by just4give** [Seeed-Studio/Seeed_Arduino_GroveAI#4]
Hi,
My goal here is to use edge impulse FOMO and get the count of objects on Wio Terminal. In order to do that, I was following this [link ](https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/seeed-grove-vision-ai) to prepare Grove Vision AI. I was able to update BL702 chip firmware. Below is the information from INFO_UF2 file

```
TinyUF2 Bootloader v1.4.0-2-g1afa03a-dirty - bouffalolab/bl_mcu_sdk (V1.4.3-8-g8742503a) sfud (heads/master) tinyusb (heads/port-bouffalolab-bl70x)
Model: Seeed Studio Grove AI
Board-ID: Grove AI
Date: Dec 16 2022
```
After that when I am trying to upload edge impulse firmware, I am unable to do that. Please see the screenshot below. 
![Screenshot 2023-03-26 200934](https://user-images.githubusercontent.com/9275193/227813927-285784ac-230e-42a2-9b00-a43e280eb560.png)

As you can imagine as I was not able to flash edge impulse firmware, daemon could not fetch the configuration to connect to EI studio. Please see the screenshot below.
![Screenshot 2023-03-26 201904](https://user-images.githubusercontent.com/9275193/227814240-e61771f1-7023-4224-934b-1f267cef8067.png)

**Expected behavior**
I should be able to update edge impulse daemon and connect to edge impulse studio.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by just4give** [comment]
I was trying to go back to as it was and updated boot loader to 2.0.0 as per instruction on [wiki ](https://wiki.seeedstudio.com/Grove-Vision-AI-Module/#update-bootloader). INFO_UF2 confirms that.

```
TinyUF2 Bootloader v2.0.0 - bouffalolab/bl_mcu_sdk (V1.4.3-8-g8742503a) sfud (heads/master) tinyusb (heads/port-bouffalolab-bl70x)
Model: Seeed Studio Grove Vision AI
Board-ID: Grove Vision AI
Date: Mar 22 2023
```
Then I restored factory firmware by following the [wiki ](https://wiki.seeedstudio.com/Grove-Vision-AI-Module/#restore-factory-firmware)

Then I flashed [person_detection_pre_17.uf2](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/download/v1.1.0/person_detection_pre_17.uf2) , connected Vision module to Wio Terminal I2C port and flashed below this program. But code froze at line 
```
if (ai.begin(ALGO_OBJECT_DETECTION, MODEL_EXT_INDEX_1)) 
```
Does this indicate my Vision AI module is not functional anymore?

**Comment by limengdu** [comment]
Hello, some time ago, due to the Windows 11 update, we found that some users were unable to upload firmware. We have fixed the problem last week and updated the Wiki content. For your problem, we suggest you can try to update Vision firmware and BootLoader firmware first according to the Wiki instructions and then retry (https://wiki.seeedstudio.com/Grove-Vision-AI-Module#restore-factory-firmware). If there are still problems, please contact our technical support email (techsupport@seeed.io) to deal with the solution so that we can follow up and reply to your questions as soon as possible, thank you for your support and understanding.

**Comment by StreakingJerry** [comment]
Hi, I have encountered the same problem with tinyuf2-grove_vision_ai_v2.0.1.bin. Not only the Edge Impulse firmware, but none of the firmware can be uploaded. My OS is Windows 10. Would you mind uploading the 2.0.0 version so that I can test it? Thank you so much.

**Comment by camow7** [comment]
I got the Vision Ai module and have the same issue. I follow the Wiki and can update bootloader to the latest but get the same problem as described here when trying to copy firmware on Windows 11.

**Comment by davidr99** [comment]
I am also having the same issue.  Has anyone found a fix for this on Windows 11?

**Comment by LynnL4** [comment]
It looks like the old bootloader version is causing firmware flashing errors on Windows 11. Please try the following steps:

Restore the factory firmware using this link: [Factory Firmware Restoration Link]
After that, upgrade the bootloader to the latest version.
Let us know if you need any help!

https://wiki.seeedstudio.com/Grove-Vision-AI-Module/#exception-processing

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
