### ISSUE TITLE
Meter detection not yet implemented?

### ISSUE THREAD

**Issue by 2ni** [Seeed-Studio/Seeed_Arduino_GroveAI#5]
**Describe the bug**
I tried to configure the GroveAi in circuitpython. The face detection example seems to work, but the meter not.
Whenever I try to set the algorithm to meter reading ([0xA0, 0x01, 0x03]), it doesn't save it. When reading the algo out, it keeps the one which was set before.
Also when I set the model to meter reading ([0xA0, 0x11, 0x13]), I get a timeout error from the device.

**To Reproduce**
1. set algo to 0x03 (meter reading) -> not saved, keeps algo which was set beforehand
2. set model to 0x13 (meter reading) -> timeout, can only set it to 0x00 or 0x11. Any other value results in a timeout error
Code:
```
result = read(bytes([0x80, 0x01]), 2)
printhex("firmware", result)
# set algo (meter: 0x03)
write(bytes([0xA0, 0x01, 0x03])) # can only set 0=object detection,1=object counting,2=classification
result = read(bytes([0xA0, 0x00]), 1)
printhex("algo (expected 0x03):", result)

# set model (meter: 0x13 according to Protocol.md, 0x01 according to meter_reading.ino. Both fail)
write(bytes([0xA0, 0x11, 0x01]))
result = read(bytes([0xA0, 0x10]), 1)
printhex("model (0x01):", result)
```

Output:
```
firmware 0x01 0x30
algo (expected 0x03): 0x01
Traceback (most recent call last):
  File "code.py", line 58, in <module>
  File "code.py", line 31, in read
OSError: [Errno 116] ETIMEDOUT
```

The Protocol.md states model=0x13 for meter reading, but according to Seeed_Arduino_GroveAI.h there's no 0x13. And the example meter_reading.ino sets model=0x01 for meter reading. But this also leads to a timeout.

I fear that the meter reading "classification" is not yet deployed to the latest code version?

**Expected behavior**
I would expect to be able to set the algo and model according to the doc or example for meter reading without leading to an error.

**Comment by LynnL4** [comment]
Hi, have you tried upgrading the firmware, are the other modes normal. https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
